name: text-summarizer
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - blas=1.1
  - ca-certificates=2022.4.26
  - certifi=2020.6.20
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libffi=3.2.1
  - libgfortran=3.0.1
  - ncurses=6.3
  - nltk=3.2.4
  - numpy=1.14.6
  - openblas=0.2.20
  - openssl=1.0.2u
  - pandas=0.22.0
  - pip=10.0.1
  - python=3.5.6
  - python-dateutil=2.8.2
  - pytz=2021.3
  - readline=7.0
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - setuptools=40.2.0
  - six=1.16.0
  - sqlite=3.33.0
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
